optimizer_config:
  type: adamw
  lr: 0.0001
  weight_decay: 0.0001
  betas:
  - 0.9
  - 0.999
scheduler_config:
  type: cosine
  T_max: 100
  eta_min: 1.0e-06
loss_config:
  type: vae
  recon_loss_type: mse
  kl_weight: 1.0
  recon_weight: 1.0
